### ISSUE TITLE
Ambiguous constructor for 'Microsoft.Extensions.Logging.LoggerFactory' .NET Core 2.1

### ISSUE THREAD

**Issue by doovewado** [JasperFx/lamar#109]
I get this error when trying to trying to run unit tests using Microsoft.AspNetCore.TestHost:

Unable to activate type 'Microsoft.Extensions.Logging.LoggerFactory'. The following constructors are ambiguous:
Void .ctor(System.Collections.Generic.IEnumerable`1[Microsoft.Extensions.Logging.ILoggerProvider], Microsoft.Extensions.Logging.LoggerFilterOptions)
Void .ctor(System.Collections.Generic.IEnumerable`1[Microsoft.Extensions.Logging.ILoggerProvider], Microsoft.Extensions.Options.IOptionsMonitor`1[Microsoft.Extensions.Logging.LoggerFilterOptions])

Calling code:
				Server = new TestServer(new WebHostBuilder()
					.UseLamar()
					.UseStartup(GetStartupType()));

Where GetStartupType() returns typeof(T) for startup of test class (where T  inherits from Microsoft.AspNetCore.Hosting.StartupBase).

Same error if code changed to:
				Server = new TestServer(new WebHostBuilder()
					.UseLamar()
					.UseStartup<TestStartup>());

I tried with both LoggingAndOptionResolving.Lamar and LoggingAndOptionResolving.AspNetCore resolving options and the error is the same.

I've managed to determine which line of code causes this behaviour by adding the Lamar projects to my solution and debugging, commenting out this line stopped the error but I'm unsure what impact that would have.

File:
Lamar.Microsoft.DependencyInjection\WebHostBuilderExtensions.cs, Line: 74
registry.For<LoggerFilterOptions>().Use(c => c.GetInstance<IOptions<LoggerFilterOptions>>().Value);

**Comment by jeremydmiller** [comment]
@doovewado What's the full stacktrace? There's nothing Lamar in that exception.

**Comment by doovewado** [comment]
Resolved the issue, need to use Startup that inherits from StartupBase<T> rather than StartupBase i.e. TestStartup : StartupBase<ServiceRegistry>

**Comment by doovewado** [comment]
Hi Jeremy

I've closed this issue.

The problem was mostly PEBCAK, the online documentation didn't clearly
indicate the inheritance for the Startup class. I updated the issue with my
notes before closing.

Regards

doove

**Comment by Benjathing** [comment]
Request to reopen, I have a very similar issue for which the suggested answer does not fix.

```C#
   public class Program
    {
        public static void Main(string[] args)
        {
            IWebHost webhost = CreateWebHostBuilder(args).Build();
            //((Container)webhost.Services).GetInstance<IStart>().Run();
            webhost.Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseLamar()
                .UseStartup<Startup>();
    }

---

    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        public void ConfigureContainer(ServiceRegistry services)
        {
            services.Configure<Configuration.Auth>("auth", Configuration);
            services.Configure<Configuration.MetadataMapping>("metadataMapping", Configuration);
            services.AddHangfire(config => config.UseSqlServerStorage(Configuration.GetConnectionString("hangFire")));
            services.AddHttpClient("graphLogin", c => {
                c.BaseAddress = new Uri("https://login.microsoftonline.com");
            });
            services.AddHttpClient("graph", c =>
            {
                c.BaseAddress = new Uri("https://graph.microsoft.com/v1.0/");
            });
            services.Scan(s =>
            {
                s.TheCallingAssembly();
                s.WithDefaultConventions();
            });
            services.AddCors();
            services.AddMvc()
                .AddJsonOptions(o =>
                {
                    o.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
                    o.SerializerSettings.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore;
                })
                .SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
            services.AddDbContext<Context>(options => options.UseSqlServer(Configuration.GetConnectionString("defaultConnection")));
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseHsts();
            }

            app.UseHangfireServer();
            app.UseHangfireDashboard();

            app.UseCors(builder => builder
                .WithOrigins("...")
                .AllowAnyHeader()
                .AllowAnyMethod()
                .AllowCredentials()
            );
            app.UseHttpsRedirection();
            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });

            app.UseStaticFiles();
        }
    }
```

I get the same error above on attempting to run `webhost.Run()` in Program.cs.
If, however, I comment out the `services.Scan(s => {})` section in ConfigureContainer, the problem no longer appears.

This issue has only recently started to occur. I narrowed it down to a new DI inject interface:
```C#
public class RunInBackground : IRunInBackground
    {
        private readonly Context context;
        private readonly ICaller caller;
        private readonly IProjects projects;
        private const int NUMATTEMPTS = 3;
        private const int DELAY = 10;

        public RunInBackground(Context context, IProjects projects, ICaller caller)
        {
            this.context = context;
            this.caller = caller;
            this.projects = projects;
        }
```

If I directly comment out IProjects, the problem disappears.
However, the IProjects interface is also called into the Projects Controller, which does not have the same issue!

**Comment by Benjathing** [comment]
Ok. Removing Lamar uncovered what I suspect is the culprit: Adding IProject to that RunInBackground resulted in a circular reference. 
Unfortunately, Lamar's error about ambiguous constructors did not make this clear.
